dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Certbot
    image: ansible-centos7
    privileged: true
    command: /usr/lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
